export const SPORTS_CATALOG = [
  { code: 'soccer', label: 'Футбол', icon: '⚽', color: '#16a34a', order: 10 },
  { code: 'futsal', label: 'Мини-футбол', icon: '⚽', color: '#16a34a', order: 11 },
  { code: 'basketball', label: 'Баскетбол', icon: '🏀', color: '#ea580c', order: 20 },
  { code: 'fitness', label: 'Фитнес', icon: '💪', color: '#db2777', order: 30 },
  { code: 'workout', label: 'Воркаут', icon: '💪', color: '#db2777', order: 31 },
  { code: 'running', label: 'Бег', icon: '🏃', color: '#0ea5e9', order: 40 },
  { code: 'athletics', label: 'Лёгкая атлетика', icon: '🏃', color: '#dc2626', order: 41 },
  { code: 'tennis', label: 'Большой теннис', icon: '🎾', color: '#ca8a04', order: 50 },
  { code: 'table_tennis', label: 'Настольный теннис', icon: '🏓', color: '#ca8a04', order: 51 },
  { code: 'badminton', label: 'Бадминтон', icon: '🏸', color: '#ca8a04', order: 52 },
  { code: 'pickleball', label: 'Пиклбол', icon: '🏸', color: '#ca8a04', order: 53 },
  { code: 'multi', label: 'Мультиспорт', icon: '🏟️', color: '#4f46e5', order: 60 },
  { code: 'cycling', label: 'Велоспорт', icon: '🚴', color: '#0d9488', order: 70 },
  { code: 'equestrian', label: 'Конный спорт', icon: '🐎', color: '#a16207', order: 80 },
  { code: 'volleyball', label: 'Волейбол', icon: '🏐', color: '#7c3aed', order: 90 },
  { code: 'beachvolleyball', label: 'Пляжный волейбол', icon: '🏐', color: '#7c3aed', order: 91 },
  { code: 'canoe', label: 'Каноэ', icon: '🛶', color: '#0891b2', order: 100 },
  { code: 'gymnastics', label: 'Гимнастика', icon: '🤸', color: '#be185d', order: 110 },
  { code: 'handball', label: 'Гандбол', icon: '🤾', color: '#ea580c', order: 120 },
  { code: 'chess', label: 'Шахматы', icon: '♟️', color: '#475569', order: 130 },
  { code: 'climbing', label: 'Скалолазание', icon: '🧗', color: '#9333ea', order: 140 },
  { code: 'ice_skating', label: 'Коньки', icon: '⛸️', color: '#0284c7', order: 150 },
  { code: 'ice_hockey', label: 'Хоккей', icon: '🏒', color: '#1e40af', order: 151 },
  { code: 'skateboard', label: 'Скейтборд', icon: '🛹', color: '#525252', order: 160 },
  { code: 'swimming', label: 'Плавание', icon: '🏊', color: '#0284c7', order: 170 },
  { code: 'shooting', label: 'Стрельба', icon: '🎯', color: '#525252', order: 180 },
  { code: 'paintball', label: 'Пейнтбол', icon: '🎯', color: '#525252', order: 181 },
  { code: 'wakeboarding', label: 'Вейкборд', icon: '🏄', color: '#0891b2', order: 190 },
  { code: 'water_ski', label: 'Водные лыжи', icon: '🎿', color: '#0891b2', order: 191 },
  { code: 'karting', label: 'Картинг', icon: '🏎️', color: '#dc2626', order: 200 },
  { code: 'baseball', label: 'Бейсбол', icon: '⚾', color: '#475569', order: 210 },
  { code: 'yoga', label: 'Йога', icon: '🧘', color: '#a855f7', order: 220 },
  { code: 'poker', label: 'Покер', icon: '🂠', color: '#475569', order: 230 },
  { code: 'pinball', label: 'Пинбол', icon: '🎱', color: '#475569', order: 240 },
];
